name: "Copy images from docker hub to  ghcr"
on:
# Manual trigger
  workflow_dispatch:

jobs:
  publish:
    name: Publish images to GHCR
    runs-on: ubuntu-latest
    steps:
      - name: Check Docker version
        run: docker --version
      - name: Docker Hub Login
        if: matrix.target_os != 'darwin'
        uses: docker/login-action@v1
        env:
          DOCKER_REGISTRY_ID: ${{ secrets.DOCKER_REGISTRY_ID }}
        with:
          username: ${{ secrets.DOCKER_REGISTRY_ID }}
          password: ${{ secrets.DOCKER_REGISTRY_PASS }}
      - name: GitHub Container Registry login
        if: matrix.target_os != 'darwin'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run script to publish images
        run: |
          curl -L https://github.com/regclient/regclient/releases/latest/download/regctl-linux-amd64 >regctl
          chmod 755 regctl
          ./regctl version
