name: "test action"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 */5 * * *'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ github.token }}
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Build and run code
        run: |
          npm install
          node ./app.js
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Inserting new data